app = "loxala-task-cocktails-dev"
primary_region = "fra"

[deploy]
  image = "ghcr.io/bojanvu23/loxala-task"

[env]
  PORT = "8000"

[secrets]
  DATABASE_URL = { source = "DATABASE_URL" }
  GITHUB_TOKEN = { source = "GITHUB_TOKEN" }

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.ports]]
  handlers = ["http"]
  port = 80

[[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443 